services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"  # Verás tu web en http://localhost
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mongo:latest
    ports:
      - "27017:27017"